version: '3.6'
services:
  go-server:
    build:
      context: ./go-app
      dockerfile: ./Dockerfile
    environment:
      ADDRESS: "0.0.0.0:8081"
    volumes:
      - ./assets/:/app/assets/
    ports:
      - "8081:8081"

  proxy:
    image: nginx
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    depends_on:
      - go-server
